name: Continuous Integration for fastapi-sample
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/fastapi-sample.yaml
      - 'exercises/01-fastapi-sample/**'
    types: [opened, synchronize, closed]

env:
  WORKING_DIRECTORY: ./exercises/01-fastapi-sample
  POETRY_HOME: /opt/poetry

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python3 - --version 1.5.1
          ln -s $POETRY_HOME/bin/poetry /usr/local/bin/poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --no-root
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run test
        run: make test-user
        working-directory: ${{ env.WORKING_DIRECTORY }}

  code_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python3 - --version 1.5.1
          ln -s $POETRY_HOME/bin/poetry /usr/local/bin/poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --no-root
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run ruff check
        run: make ruff-check
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run black check
        run: make black-check
        working-directory: ${{ env.WORKING_DIRECTORY }}

  type_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python3 - --version 1.5.1
          ln -s $POETRY_HOME/bin/poetry /usr/local/bin/poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --no-root
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run mypy
        run: make mypy
        working-directory: ${{ env.WORKING_DIRECTORY }}

  docker_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changes in Dockerfile
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'exercises/01-fastapi-sample/Dockerfile'

      - name: Lint Dockerfile
        if: steps.filter.outputs.changed == 'true'
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: 'exercises/01-fastapi-sample/Dockerfile'
          ignore: 'DL3008' # Pin versions in apt get install
