name: Continuous Integration for fastapi-sample
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/fastapi-sample.yaml
      - 'exercises/01-fastapi-sample/**'
    types: [opened, synchronize, closed]

env:
  WORKING_DIRECTORY: ./exercises/01-fastapi-sample
  POETRY_HOME: /opt/poetry

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python3 - --version 1.5.1
          ln -s $POETRY_HOME/bin/poetry /usr/local/bin/poetry

      - name: Install dependencies
        run: |
          poetry install
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run test
        run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python3 - --version 1.5.1
          ln -s $POETRY_HOME/bin/poetry /usr/local/bin/poetry

      - name: Install dependencies
        run: |
          poetry install
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run lint
        run: make lint
        working-directory: ${{ env.WORKING_DIRECTORY }}

