name: Continuous Integration for fastapi-sample
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/fastapi-sample.yaml
      - 'exercises/01-fastapi-sample/**'
    types: [opened, synchronize, closed]

env:
  WORKING_DIRECTORY: ./exercises/01-fastapi-sample

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync --locked
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run test
        run: make test-user
        working-directory: ${{ env.WORKING_DIRECTORY }}

  code_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync --locked
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run lint check
        run: make lint-check
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run format check
        run: make format-check
        working-directory: ${{ env.WORKING_DIRECTORY }}

  type_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync --locked
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run mypy
        run: make mypy
        working-directory: ${{ env.WORKING_DIRECTORY }}

  docker_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for changes in Dockerfile
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'exercises/01-fastapi-sample/Dockerfile'

      - name: Lint Dockerfile
        if: steps.filter.outputs.changed == 'true'
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: 'exercises/01-fastapi-sample/Dockerfile'
          ignore: 'DL3008' # Pin versions in apt get install
